### ISSUE TITLE
Obtain a wildcard cert for testing SSL

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#114]

**Comment by e-schultz** [comment]
@bennett000 any update on this?

**Comment by bennett000** [comment]
@e-schultz I have created a card in our Trello since this is an internal issue.  I also contacted Bertrand.

**Comment by bennett000** [comment]
@e-schultz I know I said I was moving this to Trello, but Bertrand posited that using [let's encrypt][letsEncrypt] would be faster than actually getting a certificate.  Based on a skim of the docs it might well be the case.  I will know for sure by tomorrow. 

[letsEncrypt]:https://github.com/letsencrypt/letsencrypt "Let's encrypt"
