### ISSUE TITLE
Field Test Two projects

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#118]
We have clusternator itself, and a few demo apps, but so far we only have one "real world" application.  We need to add two more real world projects to our list so we can start making the _important_ features/improvements

**Comment by SethDavenport** [comment]
Let's get augury up
Let's get sideboard deployments working from github/circleci

**Comment by SethDavenport** [comment]
augury is not up.
sideboard is up but not integrated with ci (older version of clusternator)

**Comment by SethDavenport** [comment]
@rafkhan

**Comment by SethDavenport** [comment]
Augury seems to have some webpack/css bundling issues in docker. I'll take a look.

**Comment by SethDavenport** [comment]
@rafkhan Fixed up the issues with augury's `npm start`.  The RG client ID is now set using its on environment variable (check heroku for details) and you don't need to worry about NODE_ENV any more (npm scripts set it up appropriately for you).

So clusternation should be able to proceed now.  Let me know if you run into any other issues.

Btw I also renamed the repo from 'project-augury' to 'augury'.

**Comment by bennett000** [comment]
Thanks for the project rename!

**Comment by SethDavenport** [comment]
Going to take this over now that directorate is good to go.

**Comment by SethDavenport** [comment]
Note to self: link quickstart steps to internal starter project howto.

**Comment by SethDavenport** [comment]
@rahfan: I think we need a better node base image: https://github.com/rangle/augury/pull/192 (see CI errors).

We talked about updating clusternator init's 'node' backend option to use the reverse-proxy image.

**Comment by SethDavenport** [comment]
Augury is sort of up but need to move mongoDB out of the Heroku add-on.

**Comment by SethDavenport** [comment]
master appears to be up, but not sending data.  I need to set up ssh so I can investigate more.

**Comment by bennett000** [comment]
In your `.private` directory there should be a directory called `ssh-public` the current convention is to copy a user's public key in and name it `<username>.pub`.  In some cases there might be an `id_rsa.pub` but those are errors on my part.

If the only changes are being made to `.private` and you're using git hooks to encrypt/decrypt things can get a little weird, but the GitHooks should echo documentation that attempts to explain what is happening and why.  There's definitely room for improvement in the process and hopefully a work around/fix.

The "weirdness" is that because the only file change is to `clusternator.tar.gz.asc` _and_ it happens during the hook, git does not realize there are changes to commit.  The user ends up having to commit twice.  

If any changes are made to un-encrypted files and .private files are also modified, the first commit works as normal _except_ it does _not_ include the `clusternator.tar.gz.asc` change in its log but the change does is still in fact committed.

**Comment by SethDavenport** [comment]
Thanks Michael. I ended up having to add a bogus space to my `clusternator.json` in order to have something to commit.

Would it make sense for the `clusternator generate-ssh-key` command to update the clusternator.tar.gz.asc as it's last step instead of requiring a bogus commit?

Also the guide on http://the-clusternator.rangle.io/guide/ doesn't seem to mention this flow at all - does it need to be re-deployed?

**Comment by SethDavenport** [comment]
OK so now CI is failing with:

```sh
node ./.clusternator/docker-build.js pr

node ./.clusternator/docker-build.js pr returned exit code 1

Docker Build Error: The security token included in the request is invalid. Action failed: node ./.clusternator/docker-build.js pr
```

:(

What is this token of which you speak? I only know about ci and github secrets.

https://circleci.com/gh/rangle/augury/304

**Comment by bennett000** [comment]
I think this is why you filed the other issue.  

We should probably walkthrough exactly how all the different pieces fit together with a whiteboard.  The current system is improved from December, but there's still room for a lot more improvement.  Things also need to be made clearer to the users; both in the docs/guide and in CLI output.

**Comment by SethDavenport** [comment]
For Augury
- [ ] figure out a solution for ng-oauth's dependency on global bower
- [ ] hook it up to a mongolab account

**Comment by xorgy** [comment]
Fork ng-oauth?

**Comment by SethDavenport** [comment]
If I have to, yes. https://github.com/angularjs-oauth/oauth-ng/pull/127

**Comment by SethDavenport** [comment]
Turns out npm3's flat module structure solves the issue. So I updated the Docker image to node 5.

**Comment by bennett000** [comment]
@SethDavenport the old docker image _should_ have been using npm 3.  I'm not crazy opposed to node 5 or anything, more curious as to why it wasn't using npm 3 out of the box.

**Comment by SethDavenport** [comment]
Node 4 ships with npm 2 doesn't it? I don't recall seeing anything special in the Dockerfile that would result in npm3 - but it's possible I missed it.

Anyway circleci and Heroku were def on npm2 - now its npm3 everywhere so I have consistent behaviour until cutover.

**Comment by SethDavenport** [comment]
We should make a 'clusternator base image' for clusternator - one that includes gpg, sets up the shared key, does the /home/app and swuser setup.

The we just 'FROM' than and basically do:

```Dockerfile
# Stop really verbose output
ENV NPM_CONFIG_LOGLEVEL warn

USER swuser
RUN cd /home/app/; npm set progress=false; npm install

## Expose the ports
EXPOSE 3000

USER swuser
CMD ["/home/app/.clusternator/serve.sh"]
```

I'm hoping that will go a long way to cutting down Augury's 8 minute docker build time on CI.

**Comment by SethDavenport** [comment]
I'll catch up with @rafkhan tomorrow about where that image can live.

**Comment by bennett000** [comment]
About NPM 3, our base image [_should be_](https://github.com/rangle/dockerfiles/blob/master/rangle-node/Dockerfile#L31) updating npm when it's built.

The base images should already include `gpg`

It might well be worth keeping a base-augury image with less cruft.

**Comment by SethDavenport** [comment]
#305

**Comment by SethDavenport** [comment]
Current status:

* sideboard: clusternated
* directorate: clusternated
* augury: clusternated, but Heroku's still up.  I'd like to have ZDU before I cut over, since augury is a critical system.

**Comment by bennett000** [comment]
I hope to have a PR for #294 by Monday along with other stability improvements and expanded tests.  Although I fear that might not happen until Tuesday.
