### ISSUE TITLE
Winston on CLI

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#126]

**Comment by bennett000** [comment]
as a developer I would like to be able to tune the verbosity of my logs

**Comment by e-schultz** [comment]
Log Levels
* Debug
* Verbose
* Info
* Warn
* Error

* Default to Info level
* Toggle it on the CLI with options like
* --info --i
* --verbose --v 
* etc

Todo: Identify what logging things we want to classify at what level,

**Comment by bennett000** [comment]
The easiest way to do this, and avoid checking for mutually exclusive flags (with yargs) is to use multiple `-v` flags, like some other UNIX commands.

Example:

- `clusternator` defaults to info logging
- `clusternator -v` specifies verbose logging
- `clusternator -vv` specifies debug logging
- `clusternator -vvv` specifies "silly" logging (silly is a Winston term)
- `clusternator -q` specifies errors only
- `clusternator -q -v` -q takes precedence over -v's
