### ISSUE TITLE
clusternator installs git hooks

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#129]
As a developer I do not want to the cognitive burden of having to encrypt/decrypt my credentials before/after commits, or after pulls.  Clusternator should do this automatically. 

make-private, read-private should be installable as githooks through the clusternator CLI

**Comment by bennett000** [comment]
Git hooks now work, but they still need to be auto-installed

**Comment by SethDavenport** [comment]
Works on dynamic builds but not on static ones.

**Comment by bennett000** [comment]
- [ ] githooks should be installable like `clusternator git-hook install`
- [ ] githooks should be removable like `clusternator git-hook remove`
- [ ] githooks should _not_ overwrite existing hooks
