### ISSUE TITLE
As a developer, I want to be notified once my deployment is ready

### ISSUE THREAD

**Issue by e-schultz** [rangle/the-clusternator#135]
* Update PR with deployed details - link
* Slack hooks - post to channel that it's done & with PR/link
* CLI output?

TODO: Break Down into separate stories 

Things are ready when 'ECS is stabilized'

**Comment by bennett000** [comment]
There is a working slack hook in my fork, it works from the CLI, and JavaScript.

**Comment by bennett000** [comment]
- Slack hook has been working for several commits
- PRs/Deployments finally notify when service is steady (not just when ec2 is up)

**Comment by SethDavenport** [comment]
Slack hook done.
