### ISSUE TITLE
As a developer I would like to be able to set environment settings on my app

### ISSUE THREAD

**Issue by e-schultz** [rangle/the-clusternator#136]
* Ability to list environment settings 
* Ability to add environment settings
* Ability to update/change environment settings
* Ability to have settings that apply to the master vs pr-specific branches (ie: Heroku and how settings can inherit from the main app)

**Comment by bennett000** [comment]
The way things have worked out, these requirements _might_ already be met:

- whenever a deployment happens, through PR, or the CLI it gets its config from `.private/deployments/deployment-name`
- by default there is a `pr` deployment, and a `master` deployment
- these app definition files (appDefs) let the user specify arbitrary environment variables
- these environment variables take effect on the next build for that deployment

So if I needed to add environment variables to a PR I could edit `.private/deployments/pr`, and add key/value pairs to the environment section there.

Clusternator will automatically create _two_ environment variables that will take precedence over user created variables, they are `HOST`, and `PASSPHRASE`.  with `HOST` being set to the URL of the deployment (varies depending on PR, or actual "deployment"), and PASSPHRASE comes out of the project settings.

@rafkhan does this make sense to you?
