### ISSUE TITLE
Create a private docker registry

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#140]
as an operator I would like an accessible private hub to store docker images, this can be done on AWS with Ubuntu 14.04 based on a guide found here: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-14-04

**Comment by bennett000** [comment]
AWS finally has a private registry service.  The plan is to create a private registry per project, and use AWS IAM roles to control access to the registry.  This can all be done through the AWS API:

- create private registry on project create
- destroy (with prompt/warning) private registry on project destroy
- create IAM registry role on project create
- add CLI command to revoke/renew IAM registry role
- update clusternator to use new private registries

**Comment by SethDavenport** [comment]
Done and done.
