### ISSUE TITLE
as a clusternator user I do not want to deal with managing third party access to the clusternator server

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#150]

**Comment by rafkhan** [comment]
Client CLI has no auth token support

**Comment by bennett000** [comment]
When CircleCI deploys to clusternator it notifies it with a POST request that needs an access token.  This access token should be automatically managed by clusternator, and stored in a project's `.private`

**Comment by bennett000** [comment]
This is almost done, it just needs final debugging, on init, and token reset.

**Comment by bennett000** [comment]
This needs testing, but everything is in place
