### ISSUE TITLE
Clusternator server repo

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#17]
- github repo
- npm repo
@yuri can you create a `clusternator-server` repository on npm, please and thank you :)

**Comment by e-schultz** [comment]
@rafkhan @yuri github-repo has been created for the server portion, https://github.com/rangle/the-clusternator-server

**Comment by e-schultz** [comment]
@rafkhan nothing has been pushed to the server portion yet and the repo has been there for nearly two months. What part of the code base needs to be moved there?

**Comment by rafkhan** [comment]
@e-schultz no usable progress has been made on the server component since the client still isn't fully finished yet

**Comment by rafkhan** [comment]
@e-schultz all development is being done in this repo, can you delete `clusternator-server`?
