### ISSUE TITLE
as an operator I do not want deployments running out of memory

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#181]
The memory field in task definitions specifies the minimum _free_ RAM required on the host instance, which is also the maximum _used_ memory allowed by Docker.  Currently the default is 256MB, but we will need to find a better balance for micro instances.  Some of our testing applications like Sideboard need 200-300MB of free memory, and occasionally more (during spikes).

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.19/#create-a-container

**Comment by SethDavenport** [comment]
Done - set to 512mb by default and is configurable.
