### ISSUE TITLE
As a clusternator user I would like documentation telling me how to use the clusternator

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#198]

**Comment by bennett000** [comment]
Progress has been made.  Docs are not complete, but there is:

- a system for building docs
- a [documentation website](http://the-clusternator.rangle.io "The Clusternator Documentation")

The documentation needs expansion before this card can really be marked as complete.

**Comment by SethDavenport** [comment]
Too specific - covered by other cards.
