### ISSUE TITLE
as a clusternator user I would like documentation on how to initialize a project

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#199]
Document bootstrapping a project with clusternator using Rangle's project bootstrap script.

**Comment by SethDavenport** [comment]
Tried doing a `clusternator init` this evening.  I have a couple of questions:

1) clusternator name/clusternator token: where do these come from?
2) Seems like the TLD is asked for twice (questions 3 and 10) - or are these different?
3) It failed, probably because I supplied a bogus token, which makes sense.  However the error message isn't terribly illuminating:

```
info: Clusternator: Initialization Error: Cannot read property 'then' of undefined
info: TypeError: Cannot read property 'then' of undefined
    at /home/sdavenpo/.nvm/versions/node/v5.3.0/lib/node_modules/clusternator/lib/api/0.1/js/js-api.js:113:32
    at _fulfilled (/home/sdavenpo/.nvm/versions/node/v5.3.0/lib/node_modules/clusternator/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/sdavenpo/.nvm/versions/node/v5.3.0/lib/node_modules/clusternator/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/sdavenpo/.nvm/versions/node/v5.3.0/lib/node_modules/clusternator/node_modules/q/q.js:796:13)
    at /home/sdavenpo/.nvm/versions/node/v5.3.0/lib/node_modules/clusternator/node_modules/q/q.js:556:49
    at runSingle (/home/sdavenpo/.nvm/versions/node/v5.3.0/lib/node_modules/clusternator/node_modules/q/q.js:137:13)
    at flush (/home/sdavenpo/.nvm/versions/node/v5.3.0/lib/node_modules/clusternator/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13)
```

Not launch critical, but might be worth looking into more informative error messages at some point.

**Comment by SethDavenport** [comment]
This is with 0.1.17, node 5.3.0.

**Comment by rafkhan** [comment]
Looking into this.
The tokens are generated randomly. The name comes from `package.json` if available.

**Comment by bennett000** [comment]
This is the not so graceful way clusternator handles not having AWS credentials.  Setting the environment variables `AWS_ENV_KEY`, and `AWS_ENV_SECRET` to valid AWS credentials will clear this up, but clusternator should politely inform the users that they need AWS credentials, or access to a clusternator server.

I will file an issue for this.

**Comment by SethDavenport** [comment]
OK makes sense.  I'll get the creds of you some time.  Thanks for filing the other issue.  It's not launch critical - maybe handoff critical.

**Comment by bennett000** [comment]
Progress has been made.  Docs are not complete, but there is:

- a system for building docs
- a [documentation website](http://the-clusternator.rangle.io "The Clusternator Documentation")

There _is_ some basic info on project init, but I have some plans for something more informative.
