### ISSUE TITLE
as a clusternator user I would like master URLs to stay up to date

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#278]
For the most part AWS's route53 is reliable, especially when making new DNS entries.

However when recycling DNS entries propagation can be a problem.  Currently we tear down entries and remake them.  We might do better to `UPSERT` instead.  We should also consider a TTL of 60 instead of 300

**Comment by SethDavenport** [comment]
We are moving to a model where ELBs and domains are not torn down, but reused.
