### ISSUE TITLE
`clusternator list-projects` throws an error

### ISSUE THREAD

**Issue by SethDavenport** [rangle/the-clusternator#292]
```sh
clusternator list-projects                                                                                    Options:
  --version   Show version number                                      [boolean]
  -h, --help  Show help                                                [boolean]

Cannot read property 'then' of undefined
```

**Comment by SethDavenport** [comment]
This happens when it's called and you don't have AWS creds set up.

We should be able to call it without AWS creds.  Looks like we need to supply an implementation for this function: https://github.com/rangle/the-clusternator/blob/master/src/clusternator/projectManager.js#L31

**Comment by rafkhan** [comment]
working on the server side stuff for this
