### ISSUE TITLE
as a clusternator user I would like to be able to change my project's slack channel

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#295]

**Comment by SethDavenport** [comment]
Is it published?

**Comment by mattmcfad** [comment]
@SethDavenport No, I've never published before. Is it as simple as just running `npm run release`? or do I need permissions/account on npmjs.com?

**Comment by SethDavenport** [comment]
I think you need permissions from Yuri.  I'll take care of it.

**Comment by SethDavenport** [comment]
Ok the new command is available now in 0.5.2 from npm.
