### ISSUE TITLE
`clusternator reset-shared-key` causes subsequent PR builds to fail

### ISSUE THREAD

**Issue by SethDavenport** [rangle/the-clusternator#300]
This is because the git hooks still encrypt `.private` with the old key.

`clusternator reset-shared-key` should probably update the git hook as well.

Or perhaps the git hook should query the current shared key?

**Comment by bennett000** [comment]
Git integration would be an awesome feature.  The first step would probably be for installing/managing hooks like this, down the line though getting user management through GitHub would be great.  We currently have no concept of project ownership and GitHub has all that data already.

**Comment by SethDavenport** [comment]
So i'm thinking instead of `clusternator make-private -p the-actual-key` in `.git/hooks/clusternator-pre-commit.` we could just do `clusternator make-private -p $(clusternator project shared-key)`
