### ISSUE TITLE
Bootstrap a VPC

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#60]
As developers we would like to be able to setup an AWS account to work with the clusternator with one simple command.

- need a create/tag function in the vpcManager
- need a routeTable manager

**Comment by bennett000** [comment]
- [ ] new ec2/vpc.js
- [ ] describe, list, create, destroy
- [ ] passing tests

**Comment by alanthai** [comment]
@bennett000 do you need us to remove duplicate code? eg, `awsConstants.AWS_FILTER_CTAG` looks like it's doing the same thing as `filter.createClusternator()`

**Comment by bennett000** [comment]
@alanthai _maybe_ there's definitely things in the constants files that need to be deprecated.  I'll be diving into this PR shortly
