### ISSUE TITLE
Improve Documentation For Initial CLI/Server

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#67]
We need to make sure that consumers of clusternator can figure out how to use the clusternator.

Clusternator _can_ potentially be run _manually_ from the CLI so long as the end user has AWS credentials.

Even with the clusternator server, the clusternator CLI has to be able to run a few commands like `clusternator init`, and those need to be documented

The clusternator server setup also needs to be documented, along with installing GitHub hooks, and/or circleCI hooks.

Dockerization will at least need to be bullet pointed, with links to Docker's resources.

**Comment by rafkhan** [comment]
I have this file so far: https://github.com/rangle/the-clusternator/blob/master/docs/server.md
