### ISSUE TITLE
Expose AWS Wrappers To CLI

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#80]
As a developer I would like to be able to _quickly_ create/read/update/destroy AWS resources from the command line.

The AWS wrapper commands need to be exposed to the CLI, not only for testing purposes, but for anyone that needs to manually play with AWS resources, list them, etc.

**Comment by bennett000** [comment]
@xorgy and I have made some process on this.  Local clusternator servers have working `0.1/project/create` endpoints that authenticate, and execute an AWS project create.  We're still debugging this behaviour on docker deployments.

**Comment by bennett000** [comment]
When this story is complete it will address #132 and #133

**Comment by bennett000** [comment]
- project init works on local builds now (need to test on Docker/live)
- user management, and logins work on local builds now (need to test on Docker/live)

*todo* - make sure AWS resource listing is implemented _enough_ to allow for `clusternator ssh`, `clusternator log`, and `clusternator log-ecs` to function.  This should require wiring up one more endpoint.

**Comment by bennett000** [comment]
Core features are actually done.  Tonight we will confirm some of the auxiliary commands, and then this will be complete.

**Comment by SethDavenport** [comment]
Potentially done - requires validation.

**Comment by bennett000** [comment]
We need to wire up deploy

**Comment by SethDavenport** [comment]
Deploy is done, need update and delete to work.

**Comment by SethDavenport** [comment]
Once this is done, will `.private/aws-project-credentials.json` and `.private/clusternator-aws.json` still be needed?

**Comment by bennett000** [comment]
@SethDavenport both of those should be eliminated by #310 but I need to confirm that.  There's a few AWS id's (nothing strictly secret just the ID of a VPC type thing) that are there to shortcut some things.  However with the recent fixes to our AWS module we should be able to deprecate them
