### ISSUE TITLE
as a developer I would like my Pull Request Deployments to cleanly/automatically update if I update my pull request

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#89]
- Check if PR exists
- Update taskdefs

**Comment by bennett000** [comment]
as a developer I would like my Pull Request Deployments to cleanly/automatically update *if* I update my pull request

**Comment by e-schultz** [comment]
Heroku has an issue where if you do a force-push, the review app won't get updated unless you close/re-open the PR. It's an easy work around - but would be nice if we didn't have this issue.

Not sure if this should be another story or not, but would be nice if having the PR get updated with deployment details. ie: after a successful deployment, the PR gets updated saying 'deployed to X at Y time', with 'X' being a link to the app.

**Comment by SethDavenport** [comment]
@
