### ISSUE TITLE
clusternator make-private breaks if private files are missing

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#96]

**Comment by SethDavenport** [comment]
What is the expected behaviour?  Tar an empty folder?

**Comment by bennett000** [comment]
Good question.  Things have changed a lot since this issue was filed.  I would suggest the expected behavior should be to output a message saying something like _"project has no private files"_ then the only question is do we exit with a zero status or not... I can see arguments for both cases I'm tending to lean towards exiting with zero.

**Comment by SethDavenport** [comment]
OK cool.  Sounds like something I can handle :)
